<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.streaming_platform</groupId>
    <artifactId>streaming-platform</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>streaming-platform</name>

    <!-- 🔗 Modules -->
    <modules>
        <module>api-gateway</module>
        <module>user-service</module>
        <module>video-service</module>
        <module>event-lib</module>
        <module>like-service</module>
        <module>comment-service</module>
        <module>upload-service</module>
        <module>processing-service</module>
    </modules>

    <!-- 🌍 Global Properties -->
    <properties>
        <java.version>21</java.version>
        <spring.boot.version>3.2.5</spring.boot.version>
        <spring.cloud.version>2023.0.1</spring.cloud.version>
        <jjwt-api.version>0.11.5</jjwt-api.version>
    </properties>

    <!-- 📦 Dependency Management -->
    <dependencyManagement>
        <dependencies>

            <!-- Spring Boot -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Spring Cloud -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!--  JWT MANAGEMENT  -->
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt-api.version}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt-api.version}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt-api.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <!-- 🔧 Build Plugin Management -->
    <build>
        <pluginManagement>
            <plugins>

                <!-- Spring Boot Plugin -->
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>

</project>