spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - PATH=/api/users/**
  application:
    name: api-gateway

server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: health, info