spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: video-service
          uri: http://localhost:8082
          predicates:
              - Path=/api/videos/**
        - id: like-service
          uri: http://localhost:8083
          predicates:
              - Path=/api/likes/**
        - id: comment-service
          uri: http://localhost:8084
          predicates:
              - Path=/api/comments/**
        - id: upload-service
          uri: http://localhost:8085
          predicates:
              - Path=/api/upload/**
  application:
    name: api-gateway

server:
  port: 8080


jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health, info