server:
  port: 8085

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  application:
    name: upload-service

video-service-url: ${CLIENT_URI_UPLOAD}
R2:
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket: ${R2_BUCKET}
  endpoint: ${R2_ENDPOINT}
